###
GET http://localhost:3000/products
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Galaxy S24",
    "description": "The best smartphone in the world",
    "value": 8000
}
###
GET http://localhost:3000/products/667f1376370ba6b2744c18cd
###
PATCH http://localhost:3000/products/667f1a380e243cd3928559b9
Content-Type: application/json

{
    "name": "Galaxy S24 Ultra",
    "discount": 0.15
}
###
DELETE http://localhost:3000/products/667f1376370ba6b2744c18cd